# Generated by Django 6.0.2 on 2026-03-11 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0002_answer_user_question_user_voteanswer_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='voteanswer',
            constraint=models.UniqueConstraint(fields=('answer', 'user'), name='unique_vote_answer'),
        ),
        migrations.AddConstraint(
            model_name='votequestion',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_vote_question'),
        ),
    ]
