# Generated by Django 6.0.2 on 2026-03-19 00:59

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0003_alter_voteanswer_user_alter_votequestion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=martor.models.MartorField(),
        ),
    ]
