# Generated by Django 6.0.2 on 2026-03-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0005_uuidtaggeditem_question_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-is_solution', '-created_at']},
        ),
    ]
