# Generated by Django 6.0.2 on 2026-03-27 06:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('questions_answers', '0007_alter_answer_created_at_alter_question_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('is_positive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='voteanswer',
            name='unique_vote_answer',
        ),
        migrations.RemoveConstraint(
            model_name='votequestion',
            name='unique_vote_question',
        ),
        migrations.AddField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='voteanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='voteanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='votequestion',
            name='user',
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['content_type', 'object_id'], name='questions_a_content_ac3f80_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('object_id', 'user'), name='unique_vote'),
        ),
        migrations.DeleteModel(
            name='VoteAnswer',
        ),
        migrations.DeleteModel(
            name='VoteQuestion',
        ),
    ]
